apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demo-app
  ports:
  - port: 5678
    targetPort: 5678
    nodePort: 30007
  