name: rollback
run-name: ${{ github.actor }} is doing rollback
on: 
  workflow_dispatch:
    inputs:
      github-user:
        description: 'Github user'
        required: true
        type: string
      github-app-pass:
        description: 'Password for github user'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set global user for git
        run: | 
          git config --global user.email "${{ github.actor }}"
          git config --global user.name "${{ github.actor }}"

      - name: Config remote repository URL 
        run: git remote set-url origin "https://{{ inputs.github-user }}/{{ inputs.github-app-pass }}@github.com/$GITHUB_REPOSITORY"

      - name: Revert last commit. 
        run: git revert HEAD --no-edit
        
      - name: Push changes to repository
        run: |
          echo "https://{{ inputs.github-user }}/{{ inputs.github-app-pass }}@github.com/$GITHUB_REPOSITORY"
          git push "https://{{ inputs.github-user }}/{{ inputs.github-app-pass }}@github.com/$GITHUB_REPOSITORY"